name: Build, Test, and Deploy to GCP Kubernetes

on:
  workflow_dispatch:

env:
  DOCKER_REPO: dg4285/harmonix-dev # TODO: Update your Docker Hub repository
  IMAGE_NAME: demo-gradle              # TODO: Update your service name
  PROJECT_ID: srilanka-zss-poc-d            # TODO: Update your GCP project id
  K8S_CLUSTER: harmonix-dev-cluster             # TODO: Update your Kubernetes cluster name
  K8S_REGION: us-central1            # TODO: Update your Kubernetes cluster region

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Run Unit Tests with Coverage
        run: |-
          ./gradlew test jacocoTestReport
          COVERAGE=$(./gradlew jacocoTestReport | grep 'Total Coverage' | awk '{print $NF}' | sed 's/%//')
          echo "Coverage: $COVERAGE%"
          if [ "$COVERAGE" -lt 80 ]; then
            echo "Unit test coverage is below 80%. Failing build."
            exit 1
          fi

      - name: Save Coverage Report
        run: |-
          tar -czf coverage-report.tar.gz build/reports/jacoco
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker create -v /coverage --name coverage-container busybox
          docker cp coverage-report.tar.gz coverage-container:/coverage/
          docker commit coverage-container ${{ env.DOCKER_REPO }}-coverage-report:${{ github.sha }}
          docker push ${{ env.DOCKER_REPO }}-coverage-report:${{ github.sha }}

      - name: Build and Push Docker Image
        run: |-
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker build -t ${{ env.DOCKER_REPO }}-${{ env.IMAGE_NAME }}:${{ github.sha }} .
          docker push ${{ env.DOCKER_REPO }}-${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          token_format: 'access_token'
          workload_identity_provider: projects/73029603858/locations/global/workloadIdentityPools/my-pool/providers/github-provider
          service_account: github-build-deploy-cloudrun@${{ env.PROJECT_ID }}.iam.gserviceaccount.com

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Install gke-gcloud-auth-plugin
        run: |
          gcloud components list
          echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
          sudo apt update
          sudo apt-get install google-cloud-sdk-gke-gcloud-auth-plugin
          echo "##vso[task.setvariable variable=USE_GKE_GCLOUD_AUTH_PLUGIN]True"
          gcloud components list


      - name: Connect to GCP Kubernetes Cluster
        run: |-
          gcloud container clusters get-credentials ${{ env.K8S_CLUSTER }} --region ${{ env.K8S_REGION }} --project ${{ env.PROJECT_ID }}

      - name: Deploy to GCP Kubernetes
        run: |-
          kubectl set image deployment/${{ env.IMAGE_NAME }} ${{ env.IMAGE_NAME }}=${{ env.DOCKER_REPO }}-${{ env.IMAGE_NAME }}:${{ github.sha }}
          kubectl rollout status deployment/${{ env.IMAGE_NAME }}
